server:
  port: 8081
spring:
  application:
    name: cms-acme

aws:
  region: ${AWS_REGION:A}
  dynamodb:
    endpoint: ${AWS_DYNAMODB_ENDPOINT:https://amazon.com}
    secretKey: ${AWS_SECRET_KEY:B}
    accessKey: ${AWS_ACCESS_KEY:C}


info:
  app:
    name: ${spring.application.name}
    port: ${server.port}
    description: This application is for patientAdmit process.
    version: 0.0.1

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics


