server:
  port: 8081
spring:
  application:
    name: cms-acme

# Spring Cloud Security
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: ${JWT_JWKS_URI:https://cognito-idp.us-east-1.amazonaws.com/us-east-1_HwRgngsNx/.well-known/jwks.json}


aws:
  region: ${AWS_REGION:us-east-1}
  dynamodb:
    endpoint: ${AWS_DYNAMODB_ENDPOINT:https://amazon.com}
    secretKey: ${AWS_SECRET_KEY:F7Du7CpvsrD92LjhJOM3MkuSqL38MaAgEhXtwdNJ}
    accessKey: ${AWS_ACCESS_KEY:AKIAX7PDOFWRKO6XLY4L}


info:
  app:
    name: ${spring.application.name}
    port: ${server.port}
    description: This application is for PatientStatus process.
    version: 0.0.1

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics
logging:
  level:
    root: info
    org.springframework: debug
    gov.cms.acme: debug
